### ISSUE TITLE
Update WPCS to 2.0

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-sniffs#4]
@claudiosanches, what are your thoughts on updating the version of WPCS used in this repository to 2.0?

**Comment by claudiosanches** [comment]
@rodrigoprimo I like this idea, mostly because now fully support PHP 7.3, we'll need to update the sniffs here, but seems to be easy: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-2.0.0-for-Developers-of-external-standards

Releases notes:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/2.0.0-RC1
The only thing deprecated now are the annotations, so don't sounds like too much trouble on core, since we can replace all at.
